### ISSUE TITLE
Write an interface that that goes in-between the database and the application

### ISSUE THREAD

**Issue by WheresHJ** [codeforboston/refunder#2]
Example
class DBInterface
{
  GetBudget(strBudgetName) {}
}

class GoogleSheetsDB : public DBInterface
{
  GetBudget(strBudgetName) { googleAPI.GetSheets(...)
}

**Comment by BryceStevenWilley** [comment]
This is happening in https://github.com/codeforboston/refunder/tree/test_sheets_grab, I should have an actual database interface by the end of this week.

**Comment by BryceStevenWilley** [comment]
Went in with #5. Closing
